# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# Prod environment
variables:

  # Global
  ap_vm_image: ubuntu-20.04

  # Azure DevOps
  ado_service_connection_rg: Azure-ARM-Prod
  ado_service_connection_aml_ws: Azure-ARM-Prod

  # Compute target for pipeline
  training_target: cpu-cluster
  training_target_sku: STANDARD_D2_V2
  training_target_min_nodes: 1 #Set to 0 to minimise costs
  training_target_max_nodes: 4
  training_target_tier: dedicated

  # For pipeline reference
  resource_group: <rg_name_here>
  aml_workspace: <aml_ws_name_here>
