channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pip:
      - azureml-mlflow
      - azure-identity
      - azure-ai-ml
      - scikit-learn==0.24.1
      - pandas
      - joblib
      - matplotlib
      - fastparquet